### PR TITLE
[14.0][FIX] pim

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
attribute_set need 'include_native_attribute' param in context in order to work properly

### CODE REVIEW

**Review by flotho — APPROVED** [review]
easy code review,
thanks
LGTM

**Comment by jcdrubay** [comment]
Is it possible to restart the build on runboat? Thanks

**Comment by rousseldenis** [comment]
@xavier-bouquiaux I will fix pre-commit on main branch

**Review by Cedric-Pigeon — APPROVED** [review]

**Pull request merged**
