### PR TITLE
16.0 product search multi value include product variant 

### PR DESCRIPTION
**Pull request by matthieusaison**
Hi 👋  @sbejaoui @xavier-bouquiaux @Cedric-Pigeon @sbidoul @bealdav 

Following of https://github.com/akretion/odoo-pim/pull/4 , it's the same PR but on oca/odoo-pim repo.

The related PR was merged (OCA https://github.com/OCA/odoo-pim/pull/178), can you merge this one?

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Works as expected, thanks a lot @matthieusaison 

image

**Review by PaulGoubert — APPROVED** [review]
LGTM

**Comment by bealdav** [comment]
Thanks a lot @sbidoul

**Pull request merged**
