### PR TITLE
[16.0][IMP] attribute_set: display field help

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
@rousseldenis could we reopen this one?

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Review by MarinaAForgeFlow — APPROVED** [review]
Code review. LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
ok to me

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
