### PR TITLE
[12.0][IMP] Add Addons Table and minor adjustments to the readme file

### PR DESCRIPTION
**Pull request by marcelsavegnago**
cc @rvalyi

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
up

**Comment by hparfr** [comment]
It's not done by a bot ?

**Comment by marcelsavegnago** [comment]
> It's not done by a bot ?

The update does, but to work it needs this initial inclusion in the readme.

```
[//]: # (addons)

[//]: # (end addons)
```

**Review by rvalyi — APPROVED** [review]
LGTM. It's debatable if it's really useful given it basically gives the same list of modules as the list of folders in the repo. It gives some sort of extra summary and may give a small SEO boost still, so overall I approve.

**Review by hparfr — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/community-maintainers

**Comment by marcelsavegnago** [comment]
ping

**Pull request merged**
