### PR TITLE
pim: fwd port attribute_set_completeness integration

### LINKED ISSUE #59: [13.0] attribute_set_completeness: missing values on tree view
Since the migration, 2 columns disappeared from the tree view.
I was expecting to get completion_state and completion_rate here:

image

### PR DESCRIPTION
**Pull request by simahawk**
fixes #59

depends on https://github.com/shopinvader/odoo-pim/pull/55

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]
code review ok

**Comment by szabolcsmaj** [comment]
The completeness indication and checking is completely missing from 13.0. This PR was posted 8 months ago and @Cedric-Pigeon also reviewed it. Is there something else to be done?

**Comment by simahawk** [comment]
I've integrated this commit into #55 which just got merged

**Comment by szabolcsmaj** [comment]
Thank you @simahawk for the fast response and action!

**Pull request closed without merging**
