### PR TITLE
[13.0][FIX]fix pre-commit-config file

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Update the file just as the other OCA repositories.
cc @ForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@GuillemCForgeFlow Could you do a copier update instead ?

**Comment by GuillemCForgeFlow** [comment]
@rousseldenis What do you mean by that? Which file should I update instead?

**Comment by rousseldenis** [comment]
> @rousseldenis What do you mean by that? Which file should I update instead?

The good process is to use copier to update to the last version of pre-commit and other configs.

You can follow the guide described in README here:

https://github.com/OCA/oca-addons-repo-template

The thing is to let all default answers by doing `copier update`

**Review by rousseldenis — APPROVED** [review]
Great

**Pull request merged**
