### PR TITLE
[CHG] add dedicated product view for PIM and refactor addons structure

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Review by lmignon — COMMENTED** [review]
@Cedric-Pigeon @sebastienbeau @clementmbr IMO The conceptual approach is not good at the level of the module hierarchy. The pim Addon should be the top one not the base one. It should be an app that install all the pim addons and defines the menus for all the addons on which it depends. Each addon adding new models should define security group/rules for their new models. These security group should be aggregated into high level groups into the pim app

**Review by lmignon — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
LGTM. @Cedric-Pigeon is the README adapted?

**Comment by sebastienbeau** [comment]
let's go like this.
/ocabot merge

**Pull request merged**
