### PR TITLE
[15.0][MIG] product_attribute_set

### PR DESCRIPTION
**Pull request by chandni299**
Migration from v14 to v15

### CODE REVIEW

**Review by yweng8111 — APPROVED** [review]
Nice Work!

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by GuillemCForgeFlow** [comment]
Hi @chandni299, could you please also add the changes I'm adding here: https://github.com/OCA/odoo-pim/pull/125
Thank you 😄

**Comment by chandni299** [comment]
> Hi @chandni299, could you please also add the changes I'm adding here: #125 Thank you smile

Hello, @GuillemCForgeFlow Changes are added.

**Comment by GuillemCForgeFlow** [comment]
> > Hi @chandni299, could you please also add the changes I'm adding here: #125 Thank you smile
> 
> Hello, @GuillemCForgeFlow Changes are added.

You could also cherry-pick the commit instead of adding another one!

**Pull request closed without merging**
