### PR TITLE
[13.0][IMP] attribute_set: Add attribute widget field

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Superseed https://github.com/OCA/odoo-pim/pull/68

CC @ForgeFlow

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@simahawk @qgroulard @JordiMForgeFlow 
Would you mind to do a fast review? Thanks!

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG

**Review by florian-dacosta — APPROVED** [review]
LGTM code review + tests

**Pull request merged**
