### PR TITLE
[12.0][FWD] attribute_set_mass_editing: adapt to v12/13 changes

### PR DESCRIPTION
**Pull request by simahawk**
FWD #44
Depends on https://github.com/OCA/server-ux/pull/211

### CODE REVIEW

**Comment by simahawk** [comment]
@Cedric-Pigeon @lmignon @rousseldenis anyone? :pray:

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by simahawk** [comment]
what's the policy if OCA is not merged yet?

**Comment by lmignon** [comment]
I'd rather wait a few days to see if the pr on OCA can be merged before this one.  I made a ping to @Yajo  hoping that he would come and do another review soon...

**Comment by Cedric-Pigeon** [comment]
@simahawk OCA PR has been merged. Could you update the requirements pls?

**Pull request merged**
